[package]
name = "soukousei"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "5.9.0"
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.40"
soukousei_derive = { path = "../soukousei_derive" }

[dev-dependencies]
toml = "0.7.4"

